name: Continuous Integration
on:
  push:

jobs:
  test-app:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Test application
        run: go test ./...
      - name: Compile application
        run: go build
